# Generated by Django 2.0.3 on 2018-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('chest_pain', models.CharField(max_length=120)),
                ('rest_bpress', models.IntegerField()),
                ('blood_sugar', models.CharField(max_length=120)),
                ('rest_electro', models.CharField(max_length=120)),
                ('max_heart_rate', models.IntegerField()),
                ('exercice_angina', models.CharField(max_length=120)),
            ],
        ),
    ]
