# Generated by Django 2.0.3 on 2018-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('chest_pain', models.IntegerField()),
                ('rest_bpress', models.IntegerField()),
                ('blood_sugar', models.IntegerField()),
                ('rest_electro', models.IntegerField()),
                ('max_heart_rate', models.IntegerField()),
                ('exercice_angina', models.IntegerField()),
            ],
        ),
    ]
